# Generated by Django 6.0 on 2026-02-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_rename_product_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
