# Generated by Django 6.0 on 2026-02-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_id',
        ),
    ]
