# Generated by Django 6.0 on 2026-02-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_rename_product_cart_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
